function quarkPostProcess() {
  // do stuff to an answer after it's loaded
  const id = document.querySelector(".quark_id").innerText;
  console.log('Answer ' + id + ' generated by https://github.com/mgeduld/quark-organizer');
}